import fs from "node:fs/promises";
import path from "node:path";

const HOOK_SCRIPT = `#!/bin/sh
# Generated by aicheck
npx aicheck review --staged --fail-on critical
status=$?
if [ $status -ne 0 ]; then
  echo "aicheck blocked this commit due to critical findings."
  exit $status
fi
exit 0
`;

export async function installPreCommitHook(cwd: string): Promise<string> {
  const gitDir = path.join(cwd, ".git");

  try {
    const stats = await fs.stat(gitDir);
    if (!stats.isDirectory()) {
      throw new Error();
    }
  } catch {
    throw new Error("No .git directory found. Initialize git before installing hooks.");
  }

  const hooksDir = path.join(gitDir, "hooks");
  await fs.mkdir(hooksDir, { recursive: true });

  const hookPath = path.join(hooksDir, "pre-commit");
  await fs.writeFile(hookPath, HOOK_SCRIPT, "utf8");
  await fs.chmod(hookPath, 0o755);

  return hookPath;
}
